# Katana dark palette
foreground            #d8dee9
background            #0b0e14
selection_foreground  #0b0e14
selection_background  #7aa2f7
cursor                #7aa2f7
cursor_text_color     #0b0e14

# black
color0  #1b1f27
color8  #4b5263
# red
color1  #f7768e
color9  #ff899d
# green
color2  #9ece6a
color10 #b9f27c
# yellow
color3  #e0af68
color11 #ffd280
# blue
color4  #7aa2f7
color12 #9bb8ff
# magenta
color5  #bb9af7
color13 #d3b5ff
# cyan
color6  #7dcfff
color14 #9fe1ff
# white
color7  #c0caf5
color15 #e5e9f0
